### ISSUE TITLE
Propose: custom default color

### ISSUE THREAD

**Issue by hori-ryota** [ryota2357/ddu-column-icon_filename#7]
I want to use `NormalFloat` instead of `Normal` as default icon color (for using ddc with floating window).

How about `defaultColor` option like [this](https://github.com/ryota2357/ddu-column-icon_filename/commit/550eff6414a37bc8134f665f3689aa98e873c3da) ?

**Comment by ryota2357** [comment]
Thank you for the proposal.

I added new param, `colors`.

You can override colors.default by:

```vim
call ddu#custom#patch_global('columnParams', {
  \  'icon_filename': {
  \    'colors': {
  \      'default': 'NormalFloat'
  \    }
  \  }
  \})
```

**Comment by hori-ryota** [comment]
LGTM!!

**Comment by ryota2357** [comment]
@hori-ryota 
Sorry, I changed the color palette name, `normal` to `default`.

I edited my comment above. Please check.

**Comment by hori-ryota** [comment]
nice!

(nits: fix typo `defaultl` to `default`)

**Comment by ryota2357** [comment]
fixed.
